# Generated by Django 6.0.3 on 2026-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('date_creation', models.DateField()),
            ],
            options={
                'db_table': 'entreprise',
            },
        ),
    ]
