# Generated by Django 6.0.3 on 2026-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='devise',
            field=models.CharField(choices=[('XOF', 'Franc CFA (UEMOA)'), ('GNF', 'Franc Guinéen'), ('MAD', 'Dirham Marocain'), ('EUR', 'Euro'), ('USD', 'Dollar Américain'), ('XAF', 'Franc CFA (CEMAC)')], default='XOF', max_length=10),
        ),
    ]
