# Generated by Django 6.0.3 on 2026-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_alter_entreprise_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_fin_essai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='plan',
            field=models.CharField(choices=[('essai', "Période d'essai"), ('payant', 'Abonné'), ('suspendu', 'Suspendu')], default='essai', max_length=20),
        ),
    ]
