# Generated by Django 6.0.3 on 2026-06-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0003_add_plan_date_fin_essai'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_fin_abonnement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
