# Generated by Django 6.0.3 on 2026-03-18 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Entree', 'Entrée'), ('Sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_transaction', models.DateField()),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('validee', 'Validée'), ('en_attente', 'En attente')], default='validee', max_length=20)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/')),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='categories.categorie')),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='entreprises.entreprise')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
