# Generated by Django 6.0.3 on 2026-03-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
        ('tiers', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetteFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Client', 'Client'), ('Fournisseur', 'Fournisseur')], max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('partiellement_paye', 'Partiellement payé'), ('solde', 'Soldé'), ('en_retard', 'En retard')], default='en_cours', max_length=25)),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='entreprises.entreprise')),
                ('id_tiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='tiers.tiers')),
                ('id_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dettes', to='transactions.transaction')),
            ],
            options={
                'db_table': 'dette_facture',
                'ordering': ['date_echeance'],
            },
        ),
    ]
