# Generated by Django 6.0.3 on 2026-03-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('entreprises', '0002_alter_entreprise_devise'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('nom_categorie', 'id_entreprise')},
        ),
    ]
