# Generated by Django 6.0.3 on 2026-04-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_utilisateur_id_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire')], default='gestionnaire', max_length=20),
        ),
    ]
