# Generated by Django 6.0.3 on 2026-03-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('total_entrees', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sorties', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_final', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='entreprises.entreprise')),
            ],
            options={
                'db_table': 'rapport_snapshot',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('id_entreprise', 'mois', 'annee')},
            },
        ),
    ]
