# Generated by Django 6.0.3 on 2026-03-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('type_alerte', models.CharField(choices=[('depassement_budget', 'Dépassement de budget'), ('baisse_tresorerie', 'Baisse de trésorerie'), ('echeance_dette', 'Échéance de dette'), ('anomalie', 'Anomalie')], max_length=30)),
                ('statut', models.CharField(choices=[('lue', 'Lue'), ('non_lue', 'Non lue')], default='non_lue', max_length=10)),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='entreprises.entreprise')),
            ],
            options={
                'db_table': 'alerte',
                'ordering': ['-date_emission'],
            },
        ),
    ]
