# Generated by Django 6.0.3 on 2026-03-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_limite', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('montant_consomme', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('id_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.categorie')),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='entreprises.entreprise')),
            ],
            options={
                'db_table': 'budget',
                'ordering': ['date_fin'],
            },
        ),
    ]
