# Generated by Django 6.0.3 on 2026-03-18 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Client', 'Client'), ('Fournisseur', 'Fournisseur')], max_length=20)),
                ('id_entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='entreprises.entreprise')),
            ],
            options={
                'db_table': 'tiers',
            },
        ),
    ]
